"""empty message

Revision ID: 31300d8282a8
Revises: 67969b96fd3d
Create Date: 2024-04-05 07:19:36.767411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31300d8282a8'
down_revision = '67969b96fd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('item_type')

    # ### end Alembic commands ###
