"""empty message

Revision ID: 43adb7e92efa
Revises: 2191f0ec635c
Create Date: 2024-03-23 09:32:26.295428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43adb7e92efa'
down_revision = '2191f0ec635c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
