"""empty message

Revision ID: 67969b96fd3d
Revises: 576a1162ad47
Create Date: 2024-04-04 17:25:47.552581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67969b96fd3d'
down_revision = '576a1162ad47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('item_type')

    # ### end Alembic commands ###
