"""empty message

Revision ID: 789565cb267b
Revises: 35fec4cdc5b5
Create Date: 2024-03-24 08:42:47.328568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789565cb267b'
down_revision = '35fec4cdc5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('diameter')
        batch_op.drop_column('population')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
