"""empty message

Revision ID: c7fe82683603
Revises: 7301cccb9738
Create Date: 2024-03-27 15:27:43.726612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7fe82683603'
down_revision = '7301cccb9738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('hair_color')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('gender')
        batch_op.drop_column('eye_color')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('diameter')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.drop_column('consumables')
        batch_op.drop_column('cost_in_credits')
        batch_op.drop_column('passengers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passengers', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cost_in_credits', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('consumables', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eye_color', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
