"""empty message

Revision ID: ce72dd637932
Revises: c7fe82683603
Create Date: 2024-04-03 18:23:55.302219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce72dd637932'
down_revision = 'c7fe82683603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair_color', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=250), nullable=False))

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orbital_period', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=False))

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passengers', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('consumables', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('cost_in_credits', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=250), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.drop_column('cost_in_credits')
        batch_op.drop_column('consumables')
        batch_op.drop_column('passengers')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('diameter')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('orbital_period')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('birth_year')
        batch_op.drop_column('gender')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('hair_color')

    # ### end Alembic commands ###
